In [1]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers)

[10 20 30 40]

In [2]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print(numbers * 2)

[20 40 60 80]

In [3]:
numbers = [10, 20, 30, 40]

print(numbers * 2)

[10, 20, 30, 40, 10, 20, 30, 40]

In [4]:
arr = np.zeros((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]

In [5]:
import numpy as np
arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]

In [6]:
#np.full()
arr = np.full(6,7)

print(arr)

[7 7 7 7 7 7]

In [7]:
#np.arange
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]

In [8]:
arr = np.arange(0,10,2) #to arrange even numbers in range

print(arr)

[0 2 4 6 8]

In [9]:
#np.linspace
arr = np.linspace(0, 10, 5)

print(arr)

[ 0.   2.5  5.   7.5 10. ]

In [10]:
#creating an array using random numbers
#np.random
arr = np.random.rand(5)

print(arr)

[0.19751922 0.60088756 0.57433929 0.47533834 0.29590393]

In [11]:
arr = np.random.rand(1, 100, 5)

print(arr)

[[[8.05393466e-02 9.14765015e-01 3.58838363e-04 7.34765625e-01
   6.69558350e-01]
  [2.89582056e-01 1.05514999e-01 2.79463087e-01 1.15517297e-01
   6.38223496e-01]
  [7.00938378e-01 2.88806747e-01 7.32902026e-01 5.60988585e-01
   5.32649116e-02]
  [9.64732072e-01 5.79250332e-01 5.68668917e-01 9.60176052e-01
   5.79522899e-01]
  [5.32321952e-01 5.63643127e-01 6.96190039e-01 2.06154226e-01
   7.91844259e-01]
  [4.39947851e-01 7.28579931e-01 1.98083089e-01 4.36288109e-01
   7.22955286e-01]
  [4.19329287e-01 1.79307276e-01 3.41136822e-01 1.88731000e-01
   4.81545940e-01]
  [1.79127733e-01 5.90086338e-01 1.06153943e-03 4.22299139e-01
   9.29630540e-01]
  [8.45613527e-01 2.23971026e-01 4.57308679e-02 3.68073259e-01
   1.91829777e-01]
  [2.91603176e-01 3.82068189e-01 6.02643683e-01 9.73195174e-01
   7.74902130e-01]
  [5.88658661e-02 7.89248140e-01 5.84413170e-01 9.88154714e-01
   1.62150300e-01]
  [9.55884297e-01 3.14108564e-01 7.92189326e-01 5.80625930e-01
   3.45507071e-01]
  [5.06757127e-01 8.18959697e-01 4.20441297e-01 2.67834486e-01
   9.37590617e-01]
  [8.84339021e-01 8.31517306e-01 1.43712651e-01 4.97394535e-01
   5.40276611e-01]
  [5.70642794e-01 7.79573590e-01 8.83135396e-01 2.06326838e-01
   7.56078924e-01]
  [2.74873279e-01 1.93343379e-01 7.06885172e-01 8.63846766e-01
   5.43827186e-01]
  [9.66688400e-01 2.69692294e-01 1.09998994e-01 8.44516274e-01
   6.13515283e-01]
  [2.97172808e-01 3.71632303e-01 4.58092150e-01 6.72388996e-01
   9.21433930e-01]
  [3.61068382e-01 9.58514989e-01 1.09817560e-01 9.93487426e-01
   3.04275492e-01]
  [9.31720280e-01 1.57541451e-01 2.63713104e-02 4.37665680e-01
   9.06664279e-01]
  [7.69184947e-02 8.84664596e-01 2.41220288e-01 1.68254784e-01
   4.86683940e-01]
  [8.76785174e-01 2.62016370e-01 8.74739892e-01 1.44967628e-02
   1.16344976e-01]
  [8.37719957e-01 2.66482981e-01 5.23447382e-01 6.43599795e-01
   7.97467804e-01]
  [2.65829450e-01 7.30989034e-01 3.32118230e-01 9.37000588e-01
   3.94816142e-01]
  [3.40499267e-01 9.00243471e-01 7.49682384e-01 1.37045109e-01
   2.29113473e-01]
  [2.39509067e-01 5.19860173e-01 8.19902453e-01 3.81316557e-01
   9.13247245e-02]
  [1.30171292e-01 7.40075127e-01 3.61597541e-01 4.91556179e-01
   8.68940495e-01]
  [4.89893673e-01 9.09190596e-01 6.54434116e-01 9.11459221e-01
   9.76592585e-01]
  [5.40422262e-01 6.44114118e-01 9.17930302e-01 6.69633927e-01
   7.64295457e-01]
  [8.45772332e-01 4.07565093e-01 5.37663845e-01 3.42319856e-01
   6.84645759e-01]
  [9.76121430e-01 9.48457623e-01 4.79735098e-01 8.93392021e-01
   4.34693365e-01]
  [1.83936552e-01 1.75028492e-01 6.41853282e-01 6.71491338e-01
   5.18489855e-01]
  [8.60766261e-01 9.15114910e-01 3.70825539e-01 4.24577397e-01
   4.46454509e-01]
  [3.42360442e-01 9.86360513e-01 2.96676333e-01 4.83052464e-01
   6.83635044e-01]
  [5.22047794e-01 1.49352302e-01 9.73449757e-01 1.50653045e-01
   2.58177926e-01]
  [5.78006185e-01 7.79995832e-01 1.02027338e-03 5.63028231e-01
   6.11825190e-01]
  [9.10854101e-01 1.94051103e-01 3.64522239e-01 9.02879868e-01
   6.01135324e-01]
  [6.90798145e-01 2.29330912e-01 8.39894714e-01 5.49878616e-01
   8.94773423e-01]
  [9.76191102e-02 1.28792048e-01 3.02823682e-01 5.67961991e-01
   6.98947945e-02]
  [9.49775434e-01 1.88652259e-01 9.66372009e-01 4.10955796e-01
   7.80966940e-01]
  [9.53662259e-02 3.84654179e-01 6.10477918e-01 7.74390602e-01
   2.71421216e-01]
  [6.51523816e-01 4.12310742e-01 5.21286627e-01 4.69657602e-01
   1.05147519e-01]
  [6.51286483e-01 7.93408159e-01 4.85822858e-01 7.69157693e-01
   8.77957242e-02]
  [3.21748783e-01 1.73745364e-01 4.91592710e-01 2.59289175e-01
   5.53327198e-01]
  [2.39245467e-01 1.86520261e-01 8.48315542e-01 6.16299549e-01
   3.11464621e-01]
  [6.43288174e-01 6.55331825e-02 5.65281692e-01 7.40576089e-01
   9.69634083e-01]
  [5.16715503e-01 6.21811679e-02 9.51274193e-01 5.46048834e-01
   2.28773241e-01]
  [6.97657669e-01 3.77879467e-01 1.79520417e-01 5.46633917e-01
   4.75071236e-01]
  [3.52229857e-01 1.28721298e-01 2.30827945e-01 6.79419628e-01
   2.81289301e-01]
  [1.01140267e-01 2.86287465e-01 7.53592594e-01 6.19845783e-01
   5.88798172e-01]
  [5.61084330e-01 1.41710354e-01 3.90076476e-01 7.00718196e-01
   7.25267141e-01]
  [2.62252005e-01 9.50697186e-01 6.26317953e-02 7.97659293e-02
   2.99495079e-01]
  [7.11587861e-01 5.35167848e-01 6.14899903e-01 5.55128705e-01
   2.64430589e-01]
  [8.54656433e-02 2.86735689e-01 9.03514319e-01 5.78138025e-01
   4.63696962e-01]
  [8.85088408e-01 3.25550945e-01 4.98747462e-01 6.33027153e-01
   2.40314378e-01]
  [3.54947214e-01 9.97943377e-02 8.40024806e-01 3.97105075e-01
   5.55151559e-01]
  [6.54259843e-01 3.38119728e-01 6.76745087e-01 9.55054527e-01
   9.29515333e-01]
  [7.83406797e-01 7.90230747e-01 3.70676516e-01 8.42203966e-01
   8.86120044e-02]
  [9.14407631e-01 8.42648253e-02 2.56446217e-02 3.93267686e-01
   7.19742848e-01]
  [4.92847895e-01 2.94331242e-02 8.31470948e-01 9.72930353e-01
   2.35030616e-01]
  [2.13967732e-02 2.24569952e-01 6.59651358e-01 4.14057974e-01
   6.71910863e-01]
  [7.24873571e-01 5.86472632e-01 9.13361745e-01 4.48803693e-01
   7.52787384e-01]
  [2.09534803e-01 7.02059146e-01 1.12260932e-01 6.46645893e-01
   6.09998607e-01]
  [6.68152834e-01 6.23321962e-01 5.74261080e-01 2.85490170e-01
   3.18595753e-01]
  [1.29745936e-02 9.39990174e-01 1.27604634e-01 5.21376020e-02
   1.39242785e-01]
  [1.36963956e-02 1.60805550e-01 4.50714397e-01 3.65168011e-01
   6.63127236e-01]
  [1.81550919e-01 5.17447920e-01 8.85896299e-01 7.88008361e-01
   1.17378915e-01]
  [4.22464035e-02 6.92535492e-01 2.73338732e-01 4.33827829e-01
   7.52417340e-01]
  [6.55739571e-01 8.20926970e-01 9.49156414e-01 3.87459736e-01
   9.88194297e-01]
  [3.77979576e-02 8.86842496e-01 9.63815048e-02 2.64309211e-01
   6.63093110e-01]
  [4.97986149e-01 8.27028477e-01 6.35859110e-02 5.93951164e-01
   3.12944273e-02]
  [1.85179836e-01 6.43630136e-01 6.10017816e-01 5.76258185e-01
   1.11673463e-01]
  [4.83802830e-01 6.23338780e-01 1.63306147e-01 8.99444551e-01
   4.81677305e-01]
  [2.08916937e-01 6.55987765e-01 3.73173511e-01 5.13707812e-01
   9.00522038e-01]
  [3.24835714e-01 9.31024180e-02 2.90127564e-01 9.20460616e-01
   3.01806822e-01]
  [4.80519904e-01 6.70486168e-01 1.65652097e-02 8.26885524e-01
   2.13878275e-01]
  [3.14211173e-01 4.94616739e-01 2.83921731e-01 8.62479317e-01
   3.25729164e-01]
  [2.54936339e-01 8.55947473e-01 1.81799791e-01 8.70736305e-01
   6.94297198e-01]
  [5.22517909e-01 6.57798619e-01 8.41485493e-01 1.41441116e-03
   8.29909801e-01]
  [6.44517851e-01 3.22030466e-01 4.92502218e-01 9.45330976e-01
   1.62352422e-01]
  [9.49012813e-01 4.92893367e-01 3.46120611e-02 7.57377527e-01
   2.75118281e-01]
  [4.79076873e-01 2.05134785e-01 4.30853199e-01 9.99671127e-01
   5.18447271e-01]
  [8.72215365e-01 3.93622651e-01 6.60514422e-01 9.17488541e-01
   4.80507474e-02]
  [4.79562682e-01 7.54325404e-01 6.99751101e-01 3.92273815e-01
   6.97735005e-01]
  [5.62301238e-01 8.30799754e-01 9.96061683e-02 7.81669000e-01
   1.36664511e-01]
  [3.48365744e-01 1.28458189e-01 8.00652360e-01 2.14684399e-01
   2.57511460e-01]
  [7.78785427e-02 3.29869444e-01 3.20226001e-01 7.15458530e-01
   2.88965780e-01]
  [1.03896353e-01 1.50671893e-01 9.82855899e-01 6.30775430e-01
   5.65173219e-02]
  [4.76241002e-01 6.70143274e-01 9.45121898e-01 2.88833065e-01
   4.19527805e-01]
  [8.79699940e-01 5.96172996e-01 7.41550317e-02 9.54338652e-01
   7.36783045e-01]
  [3.12638557e-02 4.63413482e-01 3.01939251e-01 9.72707865e-01
   5.28985913e-01]
  [9.26070691e-01 9.31835546e-01 9.28395302e-01 1.24955124e-03
   3.00775801e-01]
  [3.37094147e-01 7.97434784e-01 6.15062715e-01 1.23711654e-02
   3.36382212e-01]
  [7.28934381e-01 1.36835264e-01 5.40056467e-01 1.96363857e-01
   9.38313102e-02]
  [5.86501454e-01 8.54137021e-01 1.01418612e-01 3.68917208e-01
   1.33769740e-01]
  [8.69677002e-01 7.57183800e-01 7.00194769e-01 2.60604669e-01
   4.23137487e-01]
  [1.85843280e-01 1.95637766e-01 5.24012678e-01 9.48530996e-01
   2.47419219e-01]
  [9.68269313e-02 2.45926915e-01 2.19887865e-01 6.78020572e-01
   1.13697737e-01]
  [9.71813337e-01 4.35085192e-01 6.74690892e-01 2.99465225e-01
   2.72698100e-01]
  [7.00976156e-01 5.47919961e-01 1.75379621e-01 6.60565983e-01
   9.41201862e-01]]]

In [12]:
# Random 2D Array
arr = np.random.randint(1, 10, size = (3,4))

print(arr)

[[2 4 5 6]
 [5 9 8 1]
 [9 7 5 2]]

In [13]:
arr = np.array((10, 50, 20, 80, 30))

print(arr.max())
print(arr.min())

80
10

In [14]:
import pandas as pd
ages = pd.Series([20, 25, 30,  35])

print(ages)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pd

ages = pd.Series(
    [10, 20, 30],
    index=["Ali", "Ahmad", "Sara"]
)

print(ages)

In [ ]:
data = {
    "Name": ["Ali", "Ahmad", "Sara"],
    "Age": [24, 30, 28],
    "Salary": [50000, 70000, 60000]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
df[(df["Age"] > 25) & (df["Salary"] > 60000)]

In [ ]:
df[(df["Age"] < 26) | (df["Salary"] > 80000)]

In [ ]:
df = pd.DataFrame(data)

df.set_index("Name", inplace=True)
print(df)

In [25]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmad", "Sara"],
    "Age": [24, 30, 28],
    "Salary": [50000, 70000, 60000]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

df.set_index("Name", inplace=True)

print("\nAfter:")
print(df)

Before:
    Name  Age  Salary
0    Ali   24   50000
1  Ahmad   30   70000
2   Sara   28   60000

After:
       Age  Salary
Name
Ali     24   50000
Ahmad   30   70000
Sara    28   60000

# Pandas

In [ ]:
import pandas as pd

students = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 4, 5],
        "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
        "department": ["CS", "IT", "CS", "IT", "CS"],
        "age": [20, 22, 21, 23, 25]
    }
)

scores = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 6],
        "marks": [85, 90, 78, 88]
    }
)

print("Students:")
print(students)
print("\nScores:")
print(scores)

Students:
   student_id    name department  age
0           1     Ali         CS   20
1           2    Sara         IT   22
2           3   Ahmed         CS   21
3           4  Ayesha         IT   23
4           5   Usman         CS   25

Scores:
   student_id  marks
0           1     85
1           2     90
2           3     78
3           6     88

In [ ]:
pd.merge(
    students,
    scores,
    on= "student_id",
    how = "inner"
)

   student_id   name department  age  marks
0           1    Ali         CS   20     85
1           2   Sara         IT   22     90
2           3  Ahmed         CS   21     78

In [26]:
import pandas as pd

students = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 4, 5],
        "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
        "department": ["CS", "IT", "CS", "IT", "CS"],
        "age": [20, 22, 21, 23, 25]
    }
)

scores = pd.DataFrame(
    {
        "student_id": [1, 2, 3, 6],
        "marks": [85, 90, 78, 88]
    }
)

# Corrected merge
right_joined_df = pd.merge(students, scores, on="student_id", how="right")
print(right_joined_df)

   student_id   name department   age  marks
0           1    Ali         CS  20.0     85
1           2   Sara         IT  22.0     90
2           3  Ahmed         CS  21.0     78
3           6    NaN        NaN   NaN     88

In [27]:
pd.merge(
    students,
    scores,
    on= "student_id",
    how = "left"
)

   student_id    name department  age  marks
0           1     Ali         CS   20   85.0
1           2    Sara         IT   22   90.0
2           3   Ahmed         CS   21   78.0
3           4  Ayesha         IT   23    NaN
4           5   Usman         CS   25    NaN

In [30]:
students_indeexed = students.set_index("student_id")
scores_indexed = scores.set_index("student_id")

result = students_indeexed.join(scores_indexed, how="left")
print(result)

              name department  age  marks
student_id
1              Ali         CS   20   85.0
2             Sara         IT   22   90.0
3            Ahmed         CS   21   78.0
4           Ayesha         IT   23    NaN
5            Usman         CS   25    NaN

In [37]:
df1 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "marks": [85, 90]
    }
)

df2 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "age": [20, 22]
    }
)

result = pd.concat([df1, df2], axis=1)
print(result)

   name  marks  name  age
0   Ali     85   Ali   20
1  Sara     90  Sara   22

In [ ]:
left = pd.DataFrame({
    "name": ["Ali", "Sara"]
})
right = pd.DataFrame({
    "marks": [85, 90]
})

result = pd.concat([left, right], axis=1)
print(result)

   name  marks
0   Ali     85
1  Sara     90

In [38]:
df1 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "marks": [85, 90]
    }
)

df2 = pd.DataFrame(
    {
        "name": ["Ali", "Sara"],
        "age": [20, 22]
    }
)

result = pd.concat([df1, df2], axis=0, ignore_index=True)
print(result)

   name  marks   age
0   Ali   85.0   NaN
1  Sara   90.0   NaN
2   Ali    NaN  20.0
3  Sara    NaN  22.0

In [40]:
df = pd.DataFrame(
    {
        "department": ["CS", "IT", "CS", "IT", "CS"],
        "name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman"],
        "marks": [85, 90, 78, 88, 92],
        "ages": [20, 22, 21, 23, 25]
    }
)

df.groupby("department")["marks"].mean()

department
CS    85.0
IT    89.0
Name: marks, dtype: float64

In [41]:
df.groupby("department")["marks"].agg(
    ["mean", "max", "min", "count"]
)

            mean  max  min  count
department
CS          85.0   92   78      3
IT          89.0   90   88      2

In [45]:
df = pd.DataFrame(
    {
        "name": ["Ali", "Sara", "Sara", "Ahmed"],
        "age": [18, 25, 42, 65]
    }
)

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 20, 40, 60, 100],
    labels=["Young", "Adult","Middle-aged", "Senior"]
)